export type CustomDataAttrGtmClick =
  | 'header-app-title'
  | 'top-upload-cat-button'
  | 'top-fetch-random-cat-button'
  | 'top-fetch-new-arrival-cat-button'
  | 'language-menu-ja-button'
  | 'language-menu-en-button'
  | 'footer-terms-link'
  | 'footer-privacy-link'
  | 'global-menu-top-link'
  | 'global-menu-upload-cat-link'
  | 'global-menu-terms-link'
  | 'global-menu-privacy-link'
  | 'global-menu-open-button'
  | 'global-menu-close-button'
  | 'copy-markdown-from-top-images'
  | 'copy-markdown-from-created-image'
  | 'copy-markdown-from-copy-button';
